import { DiseaseCategory } from "./DoctorWillSeeYou";

export const doctorCardInitialArray: DiseaseCategory[] = [
  {
    name: "Urgent Care",
    subName: "(Sick Visit)",
    activeIconPath: "/diseaseIconWhite/vector.svg",
    inactiveIconPath: "/diseaseIconGreen/vector.svg",
    diseases: [
      "Acute Bronchitis",
      "Ear Allergies",
      "COVID-19 Rx (Paxlovid)",
      "Dental infection",
      "Ear infection",
      "flu (Influenza)",
      "Migraine relief",
      "Motion Sicknesa",
      "Nausea/Vomiting",
      "Cold Sore",
      "Pain Relief",
      "Pediatric",
      "Phone Consult",
      "Pink Eye",
      "Sinus Infection",
      "Strep Throat",
      "Stye",
      "Thrush (Oral)",
      "Respiratory Infection",
      "UTI",
    ],
  },
  {
    name: "Sexually Transmitted Diseases",
    activeIconPath: "/diseaseIconWhite/group-411.svg",
    inactiveIconPath: "/diseaseIconGreen/group-411.svg",
    diseases: [
      "Chlamydia",
      "Herpes",
      "Trich,Chlamydia,Gonorrhea",
      "Urethritis",
      "Chlamydia & Gonorrhea",
      "HIV Exposure (PEP)",
      "Trichomoniasis",
      "Ureaplasma",
      "Genital Wart",
      "HIV prevention (PEP)",
      "Unsure?",
      "Mycoplasma",
      "Gonorrhea",
    ],
  },
  {
    name: "Women's Health",
    activeIconPath: "/diseaseIconWhite/group-232.svg",
    inactiveIconPath: "/diseaseIconGreen/group-232.svg",
    diseases: [
      "Acne(Women)",
      "Anti-aging(Women)",
      "Bacterial Vaginosis",
      "Birth Control",
      "Dermatology(Women)",
      "Excessive Sweating(Women)",
      "Menstrual Suppression",
      "Pediatrics",
      "Sexual Disorder",
      "Urinary Incontinence",
      "UTI(Women)",
      "Vaginal Yeast Infection",
      "Weight loss Rx(Women)",
      "Women's Hair Loss",
    ],
  },
  {
    name: "Men's Health",
    activeIconPath: "/diseaseIconWhite/group-233.svg",
    inactiveIconPath: "/diseaseIconGreen/group-233.svg",
    diseases: [
      "Balanitis",
      "Erectile Dysfunction",
      "Excessive Sweating(men)",
      "Genitial Warts",
      "Jock Itch",
      "Men's Hair Loss",
      "Premature Ejactulation",
      "UTI(Men)",
      "Weight Loss Rx(men)",
    ],
  },
  {
    name: "Psychiatry",
    activeIconPath: "/diseaseIconWhite/group-421.svg",
    inactiveIconPath: "/diseaseIconGreen/group-421.svg",
    diseases: [
      "ADHD",
      "Depression",
      "General Anxiety",
      "Panic Disorder",
      "Social Anxiety",
    ],
  },
  {
    name: "Chronic Medical Conditions",
    activeIconPath: "/diseaseIconWhite/group-401.svg",
    inactiveIconPath: "/diseaseIconGreen/group-401.svg",
    diseases: [
      "Asthma",
      "Chronic Allergies",
      "Gerd(Acid Reflux)",
      "Gout",
      "High Cholestrol",
      "Hypertension Treatments",
      "Hypothyroidism",
      "Insomnia",
      "Migraine",
      "Prescription Refill",
      "Smoking Cessation",
      "Weight Loss Rx(Obesity)",
    ],
  },
  {
    name: "Dermatology",
    activeIconPath: "/diseaseIconWhite/group-181.svg",
    inactiveIconPath: "/diseaseIconGreen/group-181.svg",
    diseases: [
      "Abscess(Boil)",
      "Acne",
      "Anti-Aging",
      "Athlete's Foot",
      "Cellulitis",
      "Dandruff",
      "Dermmatology",
      "Eczema",
      "Excessive Sweating ",
      "Facial Wrinkles",
      "Hair Loss(Men)",
      "Hair Loss(Women)",
      "Lice",
      "Poison Ivy",
      "Psoriasis",
      "Rosacea",
      "Scables",
      "Shingles",
      "Skin Infection",
      "Skin,Nail, and Hair",
    ],
  },
  {
    name: "Miscellaneous Health",
    activeIconPath: "/diseaseIconWhite/group-391.svg",
    inactiveIconPath: "/diseaseIconGreen/group-391.svg",
    diseases: [
      "Can't Find Your Condition?",
      "Clearence/Return to work Letter",
      "Lab result Review",
      "Medical Excuse Note",
      "Rx Refill",
      "Lab testing",
      "Imaging",
    ],
  },
  {
    name: "Online prescription refill",
    activeIconPath: "/diseaseIconWhite/group-31.svg",
    inactiveIconPath: "/diseaseIconGreen/group-31.svg",
    diseases: [],
  },
];